//User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_CURR_USER = 'SET_CURR_USER'
export const GET_USER_SETTINGS = 'GET_USER_SETTINGS'
export const UPDATE_TIMEZONE = 'UPDATE_TIMEZONE'
export const GET_USERINFO = 'GET_USERINFO'
export const GET_RESIDENT_LIST = 'GET_RESIDENT_LIST'
export const LOADING_USER_DATA = 'LOADING_USER_DATA'
export const STOP_LOADING_USER_DATA = 'STOP_LOADING_USER_DATA'
export const USER_ERRORS = 'USER_ERRORS'
export const CLEAR_USER_ERRORS = 'CLEAR_USER_ERRORS'

//Alert reducer types
export const GET_ALERTING_RULES = 'GET_ALERTING_RULES'
export const POST_ALERTING_RULES = 'POST_ALERTING_RULES'
export const GET_RECENT_ALERTS = 'GET_RECENT_ALERT'
export const SET_ALERT_SUBSCRIBERS = 'SET_ALERT_SUBSCRIBERS'
export const SET_ALERTING_ERRORS = 'SET_ALERTING_ERRORS'
export const CLEAR_ALERTING_ERRORS = 'CLEAR_ALERTING_ERRORS'

// Device reducer types
export const GET_DEVICE_SETTINGS = 'GET_DEVICE_SETTINGS'
export const POST_DEVICE_SETTINGS = 'POST_DEVICE_SETTINGS'
export const GET_DEVICE_LIST = 'GET_DEVICE_LIST'
export const UPDATE_HSV_SETTINGS = 'UPDATE_HSV_SETTINGS'
export const UPDATE_DEVICE_STATUS = 'UPDATE_DEVICE_STATUS'

//Gateway reducer types
export const SET_GATEWAY_CONN = 'SET_GATEWAY_CONN'
export const SET_USER_GATEWAY = 'SET_USER_GATEWAY'


// Post reducer types
export const MEDIA_URL = 'https://fcsiotdemostorage.blob.core.windows.net'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'


//Socket
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT'
