//User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_CURR_USER = 'SET_CURR_USER'
export const GET_USER_SETTINGS = 'GET_USER_SETTINGS'
export const UPDATE_TIMEZONE = 'UPDATE_TIMEZONE'
export const GET_USERINFO = 'GET_USERINFO'
export const GET_RESIDENT_LIST = 'GET_RESIDENT_LIST'
export const LOADING_USER_DATA = 'LOADING_USER_DATA'
export const STOP_LOADING_USER_DATA = 'STOP_LOADING_USER_DATA'
export const USER_ERRORS = 'USER_ERRORS'
export const CLEAR_USER_ERRORS = 'CLEAR_USER_ERRORS'

//Alert reducer types
export const GET_ALERTING_RULES = 'GET_ALERTING_RULES'
export const POST_ALERTING_RULES = 'POST_ALERTING_RULES'
export const GET_RECENT_ALERTS = 'GET_RECENT_ALERT'
export const SET_ALERT_SUBSCRIBERS = 'SET_ALERT_SUBSCRIBERS'
export const LOADING_ALERTS = 'LOADING_ALERTS'
export const STOP_LOADING_ALERTS = 'STOP_LOADING_ALERTS'
export const LOADING_SUBSCRIBERS = 'LOADING_SUBSCRIBERS'
export const STOP_LOADING_SUBSCRIBERS = 'STOP_LOADING_SUBSCRIBERS'
export const LOADING_RULES = 'LOADING_RULES'
export const STOP_LOADING_RULES = 'STOP_LOADING_RULES'
export const SET_ALERTING_ERRORS = 'SET_ALERTING_ERRORS'
export const CLEAR_ALERTING_ERRORS = 'CLEAR_ALERTING_ERRORS'

// Device reducer types
export const GET_DEVICE_SETTINGS = 'GET_DEVICE_SETTINGS'
export const POST_DEVICE_SETTINGS = 'POST_DEVICE_SETTINGS'
export const GET_DEVICE_LIST = 'GET_DEVICE_LIST'
export const LOADING_DEVICE_DATA = 'LOADING_DEVICE_DATA'
export const STOP_LOADING_DEVICE_DATA = 'STOP_LOADING_DEVICE_DATA'
export const SET_DEVICE_ERRORS = 'SET_DEVICE_ERRORS'
export const CLEAR_DEVICE_ERRORS = 'CLEAR_DEVICE_ERRORS'

//Gateway reducer types
export const SET_GATEWAY_CONN = 'SET_GATEWAY_CONN'
export const SET_USER_GATEWAY = 'SET_USER_GATEWAY'
export const UPDATE_DEVICE_STATUS = 'UPDATE_DEVICE_STATUS'

//History reducer types
export const GET_DEVICE_HISTORY = 'GET_DEVICE_HISTORY'
export const LOADING_HISTORY = 'LOADING_HISTORY'
export const STOP_LOADING_HISTORY = 'STOP_LOADING_HISTORY'
export const SET_HISTORY_ERRORS = 'SET_HISTORY_ERRORS'
export const CLEAR_HISTORY_ERRORS = 'CLEAR_HISTORY_ERRORS'

// Post reducer types
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const GET_POSTS_FOR_APPROVAL = 'GET_POSTS_FOR_APPROVAL'
export const DELETE_POST = 'DELETE_POST'
export const APPROVE_POST = 'APPROVE_POST'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_POSTS_BY_USER= "GET_POSTS_BY_USER"
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_TIMELINE_USER = 'SET_TIMELINE_USER'
export const LOADING_POSTS = 'LOADING_POSTS'
export const STOP_LOADING_POSTS = 'STOP_LOADING_POSTS'
export const LOADING_COMMENTS = 'LOADING_COMMENTS'
export const STOP_LOADING_COMMENTS = 'STOP_LOADING_COMMENTS'
export const UPDATING_COMMENTS = 'UPDATING_COMMENTS'
export const STOP_UPDATING_COMMENTS = 'STOP_UPDATING_COMMENTS'
export const SET_POST_ERRORS = 'SET_POST_ERRORS'
export const CLEAR_POST_ERRORS = 'CLEAR_POST_ERRORS'


// UI reducer types
export const SET_UI_ERRORS = 'SET_UI_ERRORS'
export const CLEAR_UI_ERRORS = 'CLEAR_UI_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const STOP_LOADING_UI = 'STOP_LOADING_UI'
export const SET_RESPONSE = "SET_RESPONSE"
export const CLEAR_RESPONSE = "CLEAR_RESPONSE"



//Socket
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT'
